lab6/Models/Folder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace lab6.Models
{
    public class Folder
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public ICollection<File> Files { get; set; }

        [Required]
        public String Name { get; set; }
    }
}

lab6/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab6.Data;
using lab6.Models;
namespace lab6.Controllers
{
    public class FilesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilesController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        // GET: Files
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Files.Include(f => f.Folder);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Files/Details
        public async Task<IActionResult> Details(Guid? idFile)
        {
            if (idFile == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.Folder)
                .SingleOrDefaultAsync(m => m.Id == idFile);
            if (file == null)
            {
                return NotFound();
            }
            return View(file);
        }

        // GET: Files/Create
        public async Task<IActionResult> Create(Guid? idParent)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .SingleOrDefaultAsync(m => m.Id == idParent);
            if (folder == null)
            {
                return NotFound();
            }

            var folders = await _context.Folders
                .OrderBy(x => x.Name).ToListAsync();
            ViewBag.Folders = folder;
            return View(new FileEditModel());
        }

        // POST: Files/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? idParent, FileEditModel model)
        {
            if (idParent == null)
            {
                NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.file.ContentDisposition).FileName.Value.Trim('"'));
            var fileExt = Path.GetExtension(fileName);

            var folder = await _context.Folders
                .SingleOrDefaultAsync(m => m.Id == idParent);

            if (folder == null)
            {
                NotFound();
            }

            if (ModelState.IsValid)
            {
                var file = new Models.File
                {
                    FolderId = folder.Id,
                    Name = model.Name,
                    Extension = fileExt,
                    Size = (int)model.file.Length
                };
                byte[] Data = null;

                using (var binaryReader = new BinaryReader(model.file.OpenReadStream()))
                {
                    Data = binaryReader.ReadBytes((int)model.file.Length);
                }
                file.file = Data;

                file.Id = Guid.NewGuid();
                _context.Add(file);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Folders", new { idParent = folder.Id });
            }
            return View(model);
        }

        // GET: Files/Edit
        public async Task<IActionResult> Edit(Guid? idFile)
        {
            if (idFile == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .SingleOrDefaultAsync(m => m.Id == idFile);
            if (file == null)
            {
                return NotFound();
            }
            ViewBag.Files = file;
            return View(file);
        }

        // POST: Files/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid idFile, FileEditModel model)
        {
            if (idFile == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .SingleOrDefaultAsync(m => m.Id == idFile);


            if (file == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                file.Name = model.Name;

                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Folders", new { idParent = file.FolderId });
            }
            return View(model);
        }

        // GET: Files/Delete
        public async Task<IActionResult> Delete(Guid? idFile)
        {
            if (idFile == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .Include(f => f.Folder)
                .SingleOrDefaultAsync(m => m.Id == idFile);
            if (file == null)
            {
                return NotFound();
            }

            ViewBag.Files = file;
            return View(file);
        }

        // POST: Files/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid idFile)
        {
            if (idFile == null)
            {
                return NotFound();
            }

            var file = await _context.Files
                .SingleOrDefaultAsync(m => m.Id == idFile);
            if (file == null)
            {
                return NotFound();
            }
            _context.Files.Remove(file);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Folders", new { idParent = file.FolderId });
        }

        private bool FileExists(Guid id)
        {
            return _context.Files.Any(e => e.Id == id);
        }
    }
}

lab6/Controllers/FoldersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using lab6.Data;
using lab6.Models;

namespace lab6.Controllers
{
    public class FoldersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoldersController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        // GET: Folders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Folders;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Folders/Details
        public async Task<IActionResult> Details(Guid? idParent)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.Files)
                .SingleOrDefaultAsync(m => m.Id == idParent);
            if (folder == null)
            {
                return NotFound();
            }
            return View(folder);
        }

        // GET: Folders/Create
        public IActionResult Create()
        {
            return View(new Folder());
        }

        // POST: Folders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Folder model)
        {
            if (ModelState.IsValid)
            {
                model.Id = Guid.NewGuid();
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Folders/Edit
        public async Task<IActionResult> Edit(Guid? idParent)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .SingleOrDefaultAsync(m => m.Id == idParent);
            if (folder == null)
            {
                return NotFound();
            }
            return View(folder);
        }

        // POST: Folders/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid idParent, Folder model)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .SingleOrDefaultAsync(m => m.Id == idParent);

            if (folder == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                folder.Name = model.Name;

                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Folders/Delete
        public async Task<IActionResult> Delete(Guid? idParent)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .Include(f => f.Files)
                .SingleOrDefaultAsync(m => m.Id == idParent);
            if (folder == null)
            {
                return NotFound();
            }
            return View(folder);
        }

        // POST: Folders/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid idParent)
        {
            if (idParent == null)
            {
                return NotFound();
            }

            var folder = await _context.Folders
                .SingleOrDefaultAsync(m => m.Id == idParent);

            if (folder == null)
            {
                return NotFound();
            }
            _context.Folders.Remove(folder);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Folders");
        }

        private bool FolderExists(Guid id)
        {
            return _context.Folders.Any(e => e.Id == id);
        }
    }
}

lab6/Views/Folders/Create.cshtml
@model lab6.Models.Folder
@{
    ViewData["Title"] = "Create";
}
<ol class="breadcrumb breadcrumb-top">
    <li><a asp-action="Index" asp-controller="Folders">Root</a></li>
    <li><a href="#">@Model.Name</a></li>
    <li class="active">Create new folder</li>
</ol>
<h2>Create new folder</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Folders" asp-action="Create" >
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
                <a class="btn btn-default" asp-action="Index">Cancel</a>
            </div>
        </form>

    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab6/Views/Folders/Delete.cshtml
@model lab6.Models.Folder

@{
    ViewData["Title"] = "Delete";
}


<ol class="breadcrumb breadcrumb-top">
    <li><a asp-action="Index" asp-controller="Folders">Root</a></li>
    <li><a href="#">@Model.Name</a></li>
    <li class="active">Delete</li>
</ol>

<h2>Delete @Model.Name ?</h2>
<div>
    <form asp-action="Delete" asp-controller="Folders">
        <button asp-route-idParent="@Model.Id" type="submit" class="btn btn-danger">Delete</button>
        <a class="btn btn-default" asp-action="Index">Cancel</a>
    </form>
</div>

lab6/Views/Folders/Details.cshtml
@model lab6.Models.Folder

@{
    ViewData["Title"] = "Details";
}

<ol class="breadcrumb breadcrumb-top">
    <li><a asp-action="Index" asp-controller="Folders">Root</a></li>
    <li class="active">@Model.Name</li>
</ol>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group" role="group">
        <a class="btn btn-default" asp-action="Create" asp-controller="Folders"><span class="glyphicon glyphicon-plus"></span> New folder</a>
        <a class="btn btn-default" asp-action="Create" asp-route-idParent="@Model.Id" asp-controller="Files"><span class="glyphicon glyphicon-plus"></span> New file</a>
    </div>
    <div class="btn-group" role="group">
        <a class="btn btn-default" asp-route-idParent="@Model.Id" asp-action="Edit" asp-controller="Folders"><span class="glyphicon glyphicon-pencil"></span> Edit folder</a>
        <a class="btn btn-default" asp-route-idParent="@Model.Id" asp-action="Delete" asp-controller="Folders"><span class="glyphicon glyphicon-remove"></span> Delete folder</a>
    </div>
</div>
<table class="table table-bordered table-striped table-top">
    <colgroup>
        <col style="width: 60%" />
        <col style="width: 20%" />
        <col style="width: 20%" />
    </colgroup>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Type
            </th>
            <th>
                Size
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a asp-action="Index" asp-controller="Folders">
                    <span class="glyphicon glyphicon-level-up"></span>
                    ..
                </a>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>

        @foreach (var item in Model.Files)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Files" asp-route-idFile="@item.Id">
                        @if (item.file != null)
                        {
                            <span class="glyphicon glyphicon-file"></span>
                        }

                        @item.Name

                    </a>
                </td>
                <td>
                    @item.Extension
                </td>
                <td>
                    @item.Size
                </td>
            </tr>
        }

    </tbody>
</table>

lab6/Views/Folders/Edit.cshtml
@model lab6.Models.Folder
@{
    ViewData["Title"] = "Edit";
}


<ol class="breadcrumb breadcrumb-top">
    <li><a asp-action="Index" asp-controller="Folders">Root</a></li>
    <li><a href="#">@Model.Name</a></li>
    <li class="active">Edit</li>
</ol>

<h2>Edit @Model.Name</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label class="control-label">Name</label>
                <input asp-for="Name" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" asp-route-idParent="@Model.Id" class="btn btn-primary">Save</button>
                <a class="btn btn-default" href="#">Cancel</a>
            </div>
        </form>
    </div>
</div>

lab6/Views/Folders/Index.cshtml
@model IEnumerable<lab6.Models.Folder>

@{
    ViewData["Title"] = "Index";
}

<ol class="breadcrumb breadcrumb-top">
    <li class="active">Root</li>
</ol>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group" role="group">
        <a asp-action="Create" asp-controller="Folders" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> New folder</a>
    </div>
</div>
<table class="table table-bordered table-striped table-top">
    <colgroup>
        <col style="width: 60%" />
        <col style="width: 20%" />
        <col style="width: 20%" />
    </colgroup>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Type
            </th>
            <th>
                Size
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-idParent="@item.Id" asp-controller="Folders">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        @item.Name
                    </a>
                </td>
                <td>
                    Folder
                </td>
                <td>
                    -
                </td>
            </tr>
        }
    </tbody>

</table>