lab6/Controllers/ForumCategorysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using lab6.Data;
using lab6.Models;

namespace lab6.Controllers
{
    public class ForumCategorysController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumCategorysController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ForumCategorys
        public async Task<IActionResult> Index()
        {
            return View(await _context.ForumCategorys.ToListAsync());
        }

        // GET: ForumCategorys/Details
        public async Task<IActionResult> Details(Int32? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategorys
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            return View(forumCategory);
        }

        // GET: ForumCategorys/Create
        public IActionResult Create()
        {
            return View(new ForumCategory());
        }

        // POST: ForumCategorys/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ForumCategory model)
        {
            if (ModelState.IsValid)
            {
                _context.ForumCategorys.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }


        // GET: ForumCategorys/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategorys
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            return View(forumCategory);
        }

        // POST: ForumCategorys/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Int32? id, ForumCategory model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategorys
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                forumCategory.Name = model.Name;

                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: ForumCategorys/Delete
        public async Task<IActionResult> Delete(Int32? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategorys
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            return View(forumCategory);
        }

        // POST: ForumCategorys/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Int32 id)
        {
            var forumCategory = await _context.ForumCategorys.SingleOrDefaultAsync(m => m.Id == id);
            _context.ForumCategorys.Remove(forumCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DoctorExists(int id)
        {
            return _context.ForumCategorys.Any(e => e.Id == id);
        }
    }
}

lab6/Controllers/MockupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace lab6.Controllers
{
    public class MockupsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllForums()
        {
            return View();
        }

        public IActionResult SingleForum()
        {
            return View();
        }

        public IActionResult SingleTopic()
        {
            return View();
        }
    }
}

lab6/Views/Mockups/AllForums.cshtml
@{
    ViewData["Title"] = "AllForums";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Forums</h2>
<ul>
    <li> <a asp-controller="ForumCategorys" asp-action="Create">Create New Category</a></li>
</ul>

lab6/Views/Mockups/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mockups</h2>

<ul>
    <li><a asp-controller="Mockups" asp-action="AllForums">All Forums</a></li>
    <li><a asp-controller="Mockups" asp-action="SingleForum">Single Forum</a></li>
    <li><a asp-controller="Mockups" asp-action="SingleTopic">Single Topic</a></li>
</ul>

lab6/Views/Mockups/SingleForum.cshtml
@{
    ViewData["Title"] = "SingleForum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Forum 1</h2>
<p>First forum description</p>

<p>
    <a href="#">Create new topic</a>
</p>

<div class="panel panel-default">
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>
                    <a href="#" style="font-size: 1.3em">First topic</a><br />
                    admin@example.com, Monday, June 12, 2017 3:42:50 PM
                </td>
                <td style="width: 100px">
                    5 replies
                </td>
                <td style="width: 220px">
                    user@example.com<br />
                    Monday, June 12, 2017 4:12:53 PM
                </td>
            </tr>
            <tr>
                <td>
                    <a href="#" style="font-size: 1.3em">Second topic</a><br />
                    admin@example.com, Monday, June 12, 2017 3:42:50 PM
                </td>
                <td style="width: 100px">
                    0 replies
                </td>
                <td style="width: 220px">
                    admin@example.com<br />
                    Monday, June 12, 2017 3:42:50 PM
                </td>
            </tr>
            <tr>
                <td>
                    <a href="#" style="font-size: 1.3em">Third topic</a><br />
                    admin@example.com, Monday, June 12, 2017 3:42:50 PM
                </td>
                <td style="width: 100px">
                    1 reply
                </td>
                <td style="width: 220px">
                    user@example.com<br />
                    Monday, June 12, 2017 4:12:53 PM
                </td>
            </tr>
            <tr>
                <td>
                    <a href="#" style="font-size: 1.3em">Fourth topic</a><br />
                    admin@example.com, Monday, June 12, 2017 3:42:50 PM
                </td>
                <td style="width: 100px">
                    3 replies
                </td>
                <td style="width: 220px">
                    user@example.com<br />
                    Monday, June 12, 2017 4:12:53 PM
                </td>
            </tr>
        </tbody>
    </table>
</div>

lab6/Views/Mockups/SingleTopic.cshtml
@{
    ViewData["Title"] = "SingleTopic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>First topic</h2>
    <p>
        <a href="#">Reply</a>
        | <a href="#">Edit</a>
        | <a href="#">Delete</a>
        | <a href="#">Back to Forum 1</a>
    </p>

<div class="panel panel-default">
    <div class="panel-heading">
        <div>
            admin@example.com, Monday, June 12, 2017 3:42:50 PM (edited Monday, June 12, 2017 3:43:15 PM)
            | <a href="#">Edit</a>
            | <a href="#">Delete</a>
            | <a href="#">Attach</a>
        </div>
    </div>
    <div class="panel-body">
        <div class="forum-message-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus porta bibendum ante et lacinia. Sed diam massa, pulvinar sit amet commodo consectetur, tempus consequat diam. Aliquam ultrices, massa et pharetra luctus, eros libero egestas ligula, a egestas augue nulla aliquet dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec congue tellus ac odio finibus, id sagittis tellus varius. Aliquam eu consequat nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquet aliquet libero, vel faucibus mauris tincidunt id. Nullam aliquam ultricies mi. Etiam nulla nunc, pharetra a orci ultricies, varius pharetra est. Nullam quis risus tortor. Nullam lobortis scelerisque lorem, quis finibus quam venenatis ut.

            Nunc fermentum gravida ligula, non condimentum nibh luctus quis. Suspendisse potenti. Sed aliquam, odio eu dapibus molestie, nisl ipsum eleifend augue, at feugiat velit eros vitae libero. Aliquam erat volutpat. Cras euismod at metus in faucibus. Donec iaculis ac justo id rhoncus. Fusce dapibus, ligula sit amet malesuada tincidunt, nulla lorem porta arcu, rutrum rutrum turpis arcu sed urna. Aliquam in mauris condimentum, tristique odio a, viverra ipsum. Cras non odio tellus. Etiam id cursus nunc. Fusce suscipit ac quam nec malesuada. Aliquam gravida sollicitudin iaculis.
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a href="https://picsum.photos/id/237/300/300" target="__blank">
                        <img src="https://picsum.photos/id/237/300/300" alt="Attachment" />
                    </a>
                </div>
                <div class="caption">
                    <p><a href="#" class="btn btn-sm btn-danger">Delete</a></p>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a href="https://picsum.photos/id/10/300/300" target="__blank">
                        <img src="https://picsum.photos/id/10/300/300" alt="Attachment" />
                    </a>
                </div>
                <div class="caption">
                    <p><a href="#" class="btn btn-sm btn-danger">Delete</a></p>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <a href="https://picsum.photos/id/1015/300/300" target="__blank">
                        <img src="https://picsum.photos/id/1015/300/300" alt="Attachment" />
                    </a>
                </div>
                <div class="caption">
                    <p><a href="#" class="btn btn-sm btn-danger">Delete</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div>
            admin@example.com, Monday, June 12, 2017 3:42:50 PM (edited Monday, June 12, 2017 3:43:15 PM)
            | <a href="#">Edit</a>
            | <a href="#">Delete</a>
            | <a href="#">Attach</a>
        </div>
    </div>
    <div class="panel-body">
        <div class="forum-message-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus porta bibendum ante et lacinia. Sed diam massa, pulvinar sit amet commodo consectetur, tempus consequat diam. Aliquam ultrices, massa et pharetra luctus, eros libero egestas ligula, a egestas augue nulla aliquet dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec congue tellus ac odio finibus, id sagittis tellus varius. Aliquam eu consequat nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquet aliquet libero, vel faucibus mauris tincidunt id. Nullam aliquam ultricies mi. Etiam nulla nunc, pharetra a orci ultricies, varius pharetra est. Nullam quis risus tortor. Nullam lobortis scelerisque lorem, quis finibus quam venenatis ut.

            Nunc fermentum gravida ligula, non condimentum nibh luctus quis. Suspendisse potenti. Sed aliquam, odio eu dapibus molestie, nisl ipsum eleifend augue, at feugiat velit eros vitae libero. Aliquam erat volutpat. Cras euismod at metus in faucibus. Donec iaculis ac justo id rhoncus. Fusce dapibus, ligula sit amet malesuada tincidunt, nulla lorem porta arcu, rutrum rutrum turpis arcu sed urna. Aliquam in mauris condimentum, tristique odio a, viverra ipsum. Cras non odio tellus. Etiam id cursus nunc. Fusce suscipit ac quam nec malesuada. Aliquam gravida sollicitudin iaculis.
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div>
            admin@example.com, Monday, June 12, 2017 3:42:50 PM
            | <a href="#">Edit</a>
            | <a href="#">Delete</a>
            | <a href="#">Attach</a>
        </div>
    </div>
    <div class="panel-body">
        <div class="forum-message-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus porta bibendum ante et lacinia. Sed diam massa, pulvinar sit amet commodo consectetur, tempus consequat diam. Aliquam ultrices, massa et pharetra luctus, eros libero egestas ligula, a egestas augue nulla aliquet dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec congue tellus ac odio finibus, id sagittis tellus varius. Aliquam eu consequat nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquet aliquet libero, vel faucibus mauris tincidunt id. Nullam aliquam ultricies mi. Etiam nulla nunc, pharetra a orci ultricies, varius pharetra est. Nullam quis risus tortor. Nullam lobortis scelerisque lorem, quis finibus quam venenatis ut.

            Nunc fermentum gravida ligula, non condimentum nibh luctus quis. Suspendisse potenti. Sed aliquam, odio eu dapibus molestie, nisl ipsum eleifend augue, at feugiat velit eros vitae libero. Aliquam erat volutpat. Cras euismod at metus in faucibus. Donec iaculis ac justo id rhoncus. Fusce dapibus, ligula sit amet malesuada tincidunt, nulla lorem porta arcu, rutrum rutrum turpis arcu sed urna. Aliquam in mauris condimentum, tristique odio a, viverra ipsum. Cras non odio tellus. Etiam id cursus nunc. Fusce suscipit ac quam nec malesuada. Aliquam gravida sollicitudin iaculis.
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div>
            admin@example.com, Monday, June 12, 2017 3:42:50 PM
            | <a href="#">Edit</a>
            | <a href="#">Delete</a>
            | <a href="#">Attach</a>
        </div>
    </div>
    <div class="panel-body">
        <div class="forum-message-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus porta bibendum ante et lacinia. Sed diam massa, pulvinar sit amet commodo consectetur, tempus consequat diam. Aliquam ultrices, massa et pharetra luctus, eros libero egestas ligula, a egestas augue nulla aliquet dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec congue tellus ac odio finibus, id sagittis tellus varius. Aliquam eu consequat nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras aliquet aliquet libero, vel faucibus mauris tincidunt id. Nullam aliquam ultricies mi. Etiam nulla nunc, pharetra a orci ultricies, varius pharetra est. Nullam quis risus tortor. Nullam lobortis scelerisque lorem, quis finibus quam venenatis ut.

            Nunc fermentum gravida ligula, non condimentum nibh luctus quis. Suspendisse potenti. Sed aliquam, odio eu dapibus molestie, nisl ipsum eleifend augue, at feugiat velit eros vitae libero. Aliquam erat volutpat. Cras euismod at metus in faucibus. Donec iaculis ac justo id rhoncus. Fusce dapibus, ligula sit amet malesuada tincidunt, nulla lorem porta arcu, rutrum rutrum turpis arcu sed urna. Aliquam in mauris condimentum, tristique odio a, viverra ipsum. Cras non odio tellus. Etiam id cursus nunc. Fusce suscipit ac quam nec malesuada. Aliquam gravida sollicitudin iaculis.
        </div>
    </div>
</div>